### ISSUE TITLE
Data sets and layers checklist for the MDBA hub project

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#47]
Here is a complete list (I think!) of datasets and layers which need to be loaded for the MDBA project. Please reconcile with datasets already loaded and load any that have not yet been.

**DATA POINTS**
- [x] Sustainable Rivers Audit (SRA)    http://data.gov.au/dataset/sra-fishmacro2004to2013 https://github.com/AtlasOfLivingAustralia/data-management/issues/189
- [x] Basin-wide fish monitoring data set (uploaded on data.gov.au as “Implementation Period 10” of the Sustainable Rivers Audit) - treat as separate dataset http://data.gov.au/dataset/fishmacro2004to2015 https://github.com/AtlasOfLivingAustralia/data-management/issues/190
- [x] MDFRC macroinvertebrate data https://github.com/AtlasOfLivingAustralia/data-management/issues/191
- [x] MDBA phytoplankton data - 9x XLS/XLSX files in zip, some with multiple sheets of data https://github.com/AtlasOfLivingAustralia/mdba-hub/issues/46 (all done except ChemData that doesn't really fit into the Atlas at this stage due to the lack of a chemical taxonomy in the Atlas)
- [x] Waterbird data 2014 & 2015 - 2x XLSX files (Miles and I received these through email) https://github.com/AtlasOfLivingAustralia/data-management/issues/203

**SPATIAL LAYERS**
- [x] Murray-Darling Basin Boundary http://www.mdba.gov.au/river-data/spatial-data-services/spatial-information (broken link)
- [x] MDB Water Quality Zones http://data.gov.au/dataset/water-quality-zones https://github.com/AtlasOfLivingAustralia/layers-service/issues/48
- [ ] MDB acid sulphate soils   http://data.gov.au/dataset/murray-darling-basin-acid-sulfate-soils (No shapefile on data.gov.au) https://github.com/AtlasOfLivingAustralia/mdba-hub/issues/2
- [x] Wetlands GIS of the MDB   http://data.gov.au/dataset/wetlands-gis-of-the-murray-darling-basin-series-2-0 https://github.com/AtlasOfLivingAustralia/layers-service/issues/54
- [x] MDB Water Resource Plan Areas – surface water   http://data.gov.au/dataset/murray-darling-basin-water-resource-plan-areas-surface-water https://github.com/AtlasOfLivingAustralia/layers-service/issues/48
- [x] MDB Water Resource Plan Areas – groundwater http://data.gov.au/dataset/murray-darling-basin-water-resource-plan-areas-groundwater https://github.com/AtlasOfLivingAustralia/layers-service/issues/48
- [x] Surface water SDL resource units  http://data.gov.au/dataset/surface-water-sdl-resource-units https://github.com/AtlasOfLivingAustralia/layers-service/issues/48
- [x] Groundwater SDL resource units    http://data.gov.au/dataset/groundwater-sdl-resource-units https://github.com/AtlasOfLivingAustralia/layers-service/issues/48
- [x] SRA valleys   https://data.gov.au/dataset/sustainable-rivers-audit-2-valley-and-zone-spatial-layers

**Comment by ansell** [comment]
@pbrenton Could you contact MDBA and ask them for the shape files for the acid sulphate soils spatial layer. It doesn't seem to have been uploaded to data.gov.au. This was the one that I discovered yesterday but couldn't remember when we had the meeting.

**Comment by ansell** [comment]
Just waiting on the 6 remaining layers (not acid sulphate soils at this point) being pulled/pushed into the production server from spatial-test.

**Comment by ansell** [comment]
All of the datasets have been linked to the MDBA DataHub:

http://collections.ala.org.au/dataHub/show/dh10

Need to confirm/check the status of the 300K records in the phytoplankton dataset with regards to loading and indexing. As it is larger than the 50K limit for indexing during the week it will need to wait for the weekend full reindex to appear in searches.

**Comment by ansell** [comment]
All of the processed layers have been pushed into spatial.ala.org.au and appear under the "Area Management; Murray-Darling Basin" category
